### ISSUE TITLE
LanguageServer crashes trying to get `length(nothing)`

### ISSUE THREAD

**Issue by vvpisarev** [non-Jedi/eglot-jl#3] opened 2020-04-13 12:33 UTC
Occasionally, Eglot sends `nil` where LanguageServer expects an array, which crashes LanguageServer.

My actions causing the crash:
* install eglot-jl, eglot (1.5, melpa-stable), jsonrpc (1.0.9, melpa-stable)
* open any .jl file

versioninfo():
```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-suse-linux)
  CPU: Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, ivybridge)
```

File it crashes on: anything I tried. In particular: https://gist.github.com/vvpisarev/92a2c38ab31a63e63820b8e9d48e8a4a#file-sim_type-jl

Events log: https://gist.github.com/vvpisarev/92a2c38ab31a63e63820b8e9d48e8a4a#file-eglot-events
Stderr: https://gist.github.com/vvpisarev/92a2c38ab31a63e63820b8e9d48e8a4a#file-eglot-stderr

There are line 117 in events and similar ones later indicating that emacs sent messages with `:result nil`.

**Comment by non-Jedi** [comment] 2020-04-13 14:05
I'm currently running into the eglot companion issue to https://github.com/non-Jedi/lsp-julia/issues/20 on my own computer. I think I need to switch to using my own depot for vendoring in the LanguageServer.jl deps to get better reproducibility, and then we should be able to figure out what's going on with your problem.

**Comment by vvpisarev** [comment] 2020-04-13 14:44
Thanks!

Interesting... I get the `no method matching is_stdlib()`, too, but only when the default environment is used. If I'm in a package, it's `length(::Nothing)` error.
The paths in the error messages point to LanguageServer v.1.1.0-DEV and SymbolServer v.2.0.1-DEV though, not the versions from the default environment.

**Comment by non-Jedi** [comment] 2020-04-13 18:20
Could you post the events log and stderr from #5 so I don't have to debug this against an old version of LanguageServer.jl please? I have been unable to replicate thus far.

**Comment by vvpisarev** [comment] 2020-04-13 19:02
Here:
https://gist.github.com/vvpisarev/293c5ff793fbe84ea396c1d38edea3c2

The logs are for running eglot on eglot-jl.jl itself.

**Comment by non-Jedi** [comment] 2020-04-13 19:13
Looks like the problem is that eglot is responding with a nil `results` field in a `workspace/configuration` response. By my reading of [the language server protocol spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration) this should always be a list/collection (`any[]`).

I will open an issue against eglot and tag you in it to provide further information.

**Comment by non-Jedi** [comment] 2020-04-14 12:06
@vvpisarev please try again with master of eglot. This error is likely the same as https://github.com/joaotavora/eglot/issues/340 and fixed by 
5de7c55dddc14d12937e371e7f7445411c397bcd

**Comment by vvpisarev** [comment] 2020-04-14 16:54
Aha, that seems to be it.

Thank you for the help!

**Closed** 2020-04-14 17:16 UTC
